services:
  db:
    image: postgres:13
    # todo: remove if doesn't solve
    user: "${UID}:${GID}"
    volumes:
      - ./.db:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: django-pgpubsub-app
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=settings
      - ENVIRONMENT=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
